SET SERVEROUTPUT ON;

DECLARE
    marks NUMBER := 65;
BEGIN
    IF marks >= 50 THEN
        DBMS_OUTPUT.PUT_LINE('STUDENT HAS PASS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('STUDENT HAS FAIL');
    END IF;
END;
/

